In [1]:
%%capture

!pip install pandas matplotlib numpy

In [63]:
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
url = "https://api.open-meteo.com/v1/forecast"

In [4]:
latitude = -16.40
longitude = -49.15

In [5]:
params = {
        "latitude": latitude,
        "longitude": longitude,
        "hourly": ["temperature_2m", "relative_humidity_2m"],
        "timezone": "auto",
}

In [6]:
response = requests.get(url, params= params)

In [7]:
data = response.json()

In [8]:
df = pd.DataFrame({"datetime": data['hourly']['time'],
                   "temperatura": data['hourly']['temperature_2m'],
                  "humidade_relativa": data['hourly']['relative_humidity_2m']})

In [11]:
# df['datetime'] = pd.to_datetime(df['datetime'], format= '%Y-%m-%dT H:M:S')

ValueError: time data "2026-08-28T00:00" doesn't match format "%Y-%m-%dT H:M:S", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [12]:
df['datetime'] = pd.to_datetime(df['datetime'])

In [13]:
df['datetime_data'] = df['datetime'].dt.date

In [14]:
df['datetime_data']

0      2026-08-28
1      2026-08-28
2      2026-08-28
3      2026-08-28
4      2026-08-28
          ...
163    2026-09-03
164    2026-09-03
165    2026-09-03
166    2026-09-03
167    2026-09-03
Name: datetime_data, Length: 168, dtype: object

# Qual a missão?
# Um dashboard inteligente que mostra a temperatura/humidade relativa média das cinco cidades mais importantes do país além da temperatura média
# esperada.

In [ ]:
# O que eu quero desconbrir a temperatura média máxima do dia?

#AGEMC
- Ask        -  A pergunta
- Get        -  A obtenção dos dados
- Explorer   -  Exploração dos dados
- Model      -  O desenvolvemento de um modelo
- Comunicate -  A comunicação dos dados

#A Missão do Ciêntista de Dados
- Extrair Conhecimento de Dados Desorganizados

#

# 5W2h

- Oque ?
- Porquê ?
- Quando ?
- Como ?
- Onde ?
- Quem ?
- Quanto custa ?

In [16]:
df.head()

             datetime  temperatura  humidade_relativa datetime_data
0 2026-08-28 00:00:00         25.0                 47    2026-08-28
1 2026-08-28 01:00:00         24.9                 48    2026-08-28
2 2026-08-28 02:00:00         24.3                 50    2026-08-28
3 2026-08-28 03:00:00         22.9                 55    2026-08-28
4 2026-08-28 04:00:00         22.4                 57    2026-08-28

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   datetime           168 non-null    datetime64[ns]
 1   temperatura        168 non-null    float64
 2   humidade_relativa  168 non-null    int64
 3   datetime_data      168 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 5.4+ KB

In [18]:
df.describe()

                            datetime  temperatura  humidade_relativa
count                            168   168.000000         168.000000
mean   2026-08-31 11:30:00.000000256    27.695833          42.642857
min              2026-08-28 00:00:00    20.300000          17.000000
25%              2026-08-29 17:45:00    23.600000          25.000000
50%              2026-08-31 11:30:00    26.800000          35.000000
75%              2026-09-02 05:15:00    32.350000          53.500000
max              2026-09-03 23:00:00    36.300000          97.000000
std                              NaN     4.723687          22.278124

In [37]:
df['dia_semana'] = df['datetime'].dt.day_name()

In [40]:
relatorio_clima = df.groupby('datetime_data').agg({
    "temperatura": ["min", "max", "mean"],
    "humidade_relativa": ["min", "max", "mean"]
}).reset_index()

In [24]:
relatorio_clima.to_json()

'{"(\'datetime_data\', \'\')":{"0":1787875200000,"1":1787961600000,"2":1788048000000,"3":1788134400000,"4":1788220800000,"5":1788307200000,"6":1788393600000},"(\'temperatura\', \'min\')":{"0":22.0,"1":21.1,"2":23.2,"3":24.1,"4":22.6,"5":20.4,"6":20.3},"(\'temperatura\', \'max\')":{"0":34.0,"1":34.8,"2":35.6,"3":36.3,"4":35.6,"5":33.5,"6":27.7},"(\'temperatura\', \'mean\')":{"0":27.775,"1":28.2666666667,"2":29.1708333333,"3":29.925,"4":28.9041666667,"5":26.0958333333,"6":23.7333333333},"(\'humidade_relativa\', \'min\')":{"0":22,"1":20,"2":19,"3":17,"4":18,"5":32,"6":53},"(\'humidade_relativa\', \'max\')":{"0":58,"1":52,"2":39,"3":39,"4":57,"5":97,"6":92},"(\'humidade_relativa\', \'mean\')":{"0":38.9166666667,"1":34.375,"2":28.8333333333,"3":26.1666666667,"4":30.0,"5":61.9583333333,"6":78.25}}'

In [27]:
relatorio_clima['temperatura']['max'] # Dicionário de dicionários, acessamo um dicionário e um dicionário no interior de outros

0    34.0
1    34.8
2    35.6
3    36.3
4    35.6
5    33.5
6    27.7
Name: max, dtype: float64

In [45]:
clima_amanha = relatorio_clima.loc[1].copy()

In [49]:
clima_amanha['temperatura']

min          21.1
max          34.8
mean    28.266667
Name: 1, dtype: object

In [80]:
clima_amanha["datetime_data"]

    2026-08-29
Name: 1, dtype: object

In [ ]:
# Uma função que retorna o clima e a temperatura de amanhã

In [ ]:
params = {"latitude": latitude,
"longitude": longitude,
"hourly": ["temperature_2m", "relative_humidity_2m"],
"timezone": "auto",}

In [87]:
def clima(latitude: float, longitude: float):

    """
        Uma função que retorna o clima temperatura e humidade (máxima e mínima)
        esperadas para o próximo dia.
    """

    url = "https://api.open-meteo.com/v1/forecast"

    params = {
        "latitude": latitude,
        "longitude": longitude,
        "hourly": ["temperature_2m", "relative_humidity_2m"],
        "timezone": "auto"
    }

    response = requests.get(url, params)
    # print("resposta_obtida")

    # print(response)

    # Transformando a definição em um json.
    data = response.json()

    # print("Data obtida")

    # Criando um DataFrame
    df = pd.DataFrame({
        "data": pd.to_datetime(data['hourly']['time']),
        "temperatura": data['hourly']['temperature_2m'],
        "humidade_relativa": data['hourly']['relative_humidity_2m']
    })


    # Uma coluna apenas com a data dia/mês/ano
    df['data_dia'] = df['data'].dt.date

    previsao_climatica = df.groupby('data_dia').agg({
        "temperatura": ["min", "max", "mean"],
        "humidade_relativa": ["min", "max", "mean"]
    }).reset_index()


    previsao_amanha = previsao_climatica.loc[1].copy()

    # print(previsao_amanha)

    dia = previsao_amanha['data_dia']
    temp = previsao_amanha['temperatura']
    humid = previsao_amanha['humidade_relativa']

    return {
        "dia": dia,
        "temperatura": {"min": temp['min'], "max": temp["max"], "mean": temp["mean"]},
        "humidade": {"min": humid['min'], "max": humid['max'], "mean": humid["mean"]}
    }

In [ ]:
df = pd.DataFrame({"datetime": data['hourly']['time'],
                   "temperatura": data['hourly']['temperature_2m'],
                  "humidade_relativa": data['hourly']['relative_humidity_2m']})

In [50]:
print(url)

https://api.open-meteo.com/v1/forecast

In [ ]:
latitude = -16.40
longitude = -49.15

In [89]:
clima_goiania = clima(-16.40, -49.15)

In [90]:
clima_goiania

{'dia':     2026-08-29
 Name: 1, dtype: object,
 'temperatura': {'min': np.float64(21.1),
  'max': np.float64(34.8),
  'mean': np.float64(28.266666666666666)},
 'humidade': {'min': np.int64(20),
  'max': np.int64(52),
  'mean': np.float64(34.375)}}